---
extends: default
ignore: |
  node_modules/
  .venv/
  .tox/
  dist/
  build/
rules:
  line-length:
    max: 120
    level: warning
  truthy:
    allowed-values:
      - "true"
      - "false"
    level: warning
  document-start: disable
  comments:
    min-spaces-from-content: 1
