# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2026
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
name: Scheduled Versions verification
# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "0 0 * * 5"
  workflow_dispatch:
permissions: read-all
jobs:
  check-versions:
    name: Update Managed Version Files
    permissions:
      contents: write
      pull-requests: write
    uses: electrocucaracha/gh-workflows/.github/workflows/update.yml@7362342ec4b465d80999556fae6bb61b3e56f010 # v7.0.8
    secrets:
      WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
  check-dockerfile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Update Dockerfile dependencies
        uses: renovatebot/github-action@9fea9f0fbf80401026d11d03911d62b1f70fef1f # v46.3.3
        with:
          configurationFile: .github/renovate.json
          renovate-version: 44.50.3
          token: ${{ secrets.WORKFLOW_TOKEN }} # zizmor: ignore[secrets-outside-env]
        env:
          RENOVATE_ONBOARDING: false
          RENOVATE_REQUIRE_CONFIG: optional
